services:
  db:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    env_file:
      - .env

  backend:
    build: .
    volumes:
      - ./:/backend
    env_file:
      - .env
    command: sh -c "uvicorn src.main:app --reload  --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  pg-data:
  kafka-data: