# Generated by Django 5.1.5 on 2025-01-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='Уникальный идентификатор')),
                ('cpu', models.PositiveIntegerField(editable=False, verbose_name='Количество ядер CPU')),
                ('ram', models.PositiveIntegerField(editable=False, verbose_name='Объем RAM (ГБ)')),
                ('hdd', models.PositiveIntegerField(editable=False, verbose_name='Объем HDD (ГБ)')),
                ('status', models.CharField(choices=[('started', 'Запущен'), ('blocked', 'Заблокирован'), ('stopped', 'Остановлен')], default='started', max_length=20, verbose_name='Статус сервера')),
                ('server_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Пароль от сервера')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
                'db_table': 'db_vps',
            },
        ),
    ]
